### ISSUE TITLE
explicit import scapy.config required regression vs. python2

### ISSUE THREAD

**Issue by ppietikainen** [phaethon/scapy#10]
This used to work: 

Python 3.4.1 (default, Nov  3 2014, 14:38:10)
[GCC 4.9.1 20140930 (Red Hat 4.9.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.volatile import RandIP, RandMAC, RandByte, RandNum, RandIP6
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/scapy/volatile.py", line 11, in <module>
    from .base_classes import Net
  File "/usr/lib/python3.4/site-packages/scapy/base_classes.py", line 15, in <module>
    import scapy.config
  File "/usr/lib/python3.4/site-packages/scapy/config.py", line 12, in <module>
    import scapy.base_classes as base_classes
AttributeError: 'module' object has no attribute 'base_classes'

and now I need to do import scapy.config before doing that (and also "from scapy.route import Route" to get some side-effects from that class, but that was also with python2). 

I suspect most people use from scapy.all import *, which pollutes your namespace quite badly + takes a measurable amount of extra time.

**Comment by phaethon** [comment]
Probably I moved around some import statements.
The actual issue is - in original scapy it was not exactly clear from documentation or otherwise which modules/classes are supposed to be used by the user and which are meant for internal use. Neither documentation nor test cases suggest importing Rand... classes.
For me - importing scapy.config does not sound so bad.

**Comment by ppietikainen** [comment]
Changing config.py to do:

-import scapy.base_classes as base_classes
+import scapy.base_classes  

+ changing references to base_classes.Packet_metaclass into scapy.base_classes.Packet_metaclass

seems to do the trick. 

You're right about the lack of defined API, same happens with say
scapy.layers.l2.Ether, though.

**Comment by phaethon** [comment]
Changed in last commit to import scapy.base_classes as per suggestion
