### ISSUE TITLE
Question: Can't get scapy working using python 3.5

### ISSUE THREAD

**Issue by bneedy** [phaethon/scapy#104]
I am running this code:

`from scapy.all import *
sniff(filter="ip", prn=lambda x:x.sprintf("{IP:%IP.src% -> %IP.dst%\n}"))`

and I get past the import fine, but when I get to the sniff part nothing happens.  I am unsure why it won't find anything.  If I run the same thing with a timeout it will actually end and I will get nothing.  Any reason why I wouldn't be receiving any data?  I have WinPcap installed.

**Comment by olliegg123** [comment]
Same problem here, always '<Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>'

**Comment by teprrr** [comment]
Works just fine here. Maybe it is listening on a wrong interface? Try passing network interface with iface=<interface>.

**Comment by johnthagen** [comment]
`sniff()` worked for me in Python 3.6.0 (installed from source) on Ubuntu 16.04.1 x64.

**Comment by phaethon** [comment]
@bneedy You are using Windows, right? It always helps when you add your OS, python version, exact version of scapy and how you installed it (github code, pip, ubuntu package, etc.).
What is the interface you try to use? On Windows there are common issues with packet sniffing on wireless and localhost interfaces for most packet sniffing tools (including wireshark, etc.). Please, add conf.iface and conf.route values (just write those in scapy shell and their value will be returned).
