### ISSUE TITLE
sniff issue!

### ISSUE THREAD

**Issue by netneo** [phaethon/scapy#106]
Even running multiple example codes (including yours!) I cannot get sniff to work as it throws an error.

Error being seen:

Traceback (most recent call last):
    sniff(iface='wlan1'', prn=PacketHandler())
TypeError: PacketHandler() missing 1 required positional argument: 'p'

**Comment by netneo** [comment]
Example code throwing errors:

def PacketHandler(pkt):
         access_points = []
         if pkthaslayer(Dot11):
                if pkt.type == 0 and pkt.subtype == 8:
                    if pkt.addr2 not in access_points:
                        access_points.append(pkt.addr2)
                        print('BSSID: {}\t ESSID: {}'.format(pkt.addr2,pkt.info))

**Comment by teprrr** [comment]
Are you sure those linked scripts do not work? The error in your case is that you should pass reference to your callback, not call it directly.

So sniff(iface='wlan0', prn=PacketHandler) should work.

**Comment by netneo** [comment]
thanks for responding :+1: 

I originally tried the expected "prn=PacketHandler" but then the sniff produces no output (seems to freeze?)

The script I am trying is a working python 2.7 script changed to work in python 3:

ORIGINAL SCRIPT (confirmed working)
`#!/usr/bin/env python

from scapy.all import *

ap_list = []

def PacketHandler(pkt) :

  if pkt.haslayer(Dot11) :
		if pkt.type == 0 and pkt.subtype == 8 :
			if pkt.addr2 not in ap_list :
				ap_list.append(pkt.addr2)
				print "AP MAC: %s with SSID: %s " %(pkt.addr2, pkt.info)


sniff(iface="wlan1", prn = PacketHandler)`

MY VERSION:
`#!/usr/bin/env python

from scapy.all import *

ap_list = []

def PacketHandler(pkt) :
    if pkt.type == 0 and pkt.subtype == 8 :
        if pkt.addr2 not in ap_list :
            ap_list.append(pkt.addr2)
            print("AP MAC: {} with SSID: {} ".format(pkt.addr2, pkt.info))


sniff(iface="wlan0", prn=PacketHandler)`

**Comment by netneo** [comment]
Thank you SO much for looking into this.  I am now up and working.
You where so certain that everything should be working I went a little drastic and removed my install of scapy and re-downloaded it.  After a new install everything seems to now be working!!!!
Not sure what caused the initial problems but everything no seems fine :) :+1:
