### ISSUE TITLE
switch from PyCrypto to cryptography lib 

### ISSUE THREAD

**Issue by phaethon** [phaethon/scapy#119]
This originally appeared on secdev/scapy, but seems to be useful for applying here, too. I am going to review and integrate code originally developed by @ThomasFaivre . If anybody is willing to assist on this, welcome. @robin-jarry interested?

**Comment by robin-jarry** [comment]
Hi @phaethon,

I didn't know about this python 3 compat fork :-)

Have you discussed with @p-l- and @guedou about merging it upstream ? I think this could be welcomed.

Since 2.3.3, python 2.5 compat has been officially dropped. Maybe py3 support will fit more easily.

**Comment by phaethon** [comment]
Just made WEP test pass in my local repository, but apparently I have to port changes by @mtury to layers/tls/* before I can merge in the complete patch.

**Comment by ThomasFaivre** [comment]
Hello!

I may be able to find patches that do not require the layer/tls changes if you'd like! I can check it out tomorrow!

**Comment by phaethon** [comment]
@ThomasFaivre that would be great.

**Comment by guedou** [comment]
@robin-jarry as explained on the Scapy ML, we will be pleased to welcome contributions from scapy3k to secdev/scapy. Any help is more than welcome. Python 3 is not currently on our roadmap, but Scapy 2.3.3 does make the transition smoother.

From the beginning, @phaethon chose not to contribute any fixes. At some point in time, he also [aggressively](https://bitbucket.org/secdev/scapy/issues/5106/oserror-device-not-configured) advocated scapy3k, which is not a helpful behaviour. We believe that linking to scapy3k without any contribution is not fair for all of the people helping us to improve Scapy. It is of course not a final decision, and we could reconsider it upon receiving PRs and support.

**Comment by phaethon** [comment]
@guedou , and this comment of yours was definitely not aggressive, especially, taking into account that the issue under which you write it is on cryptography module :)

**Comment by phaethon** [comment]
I ended up merging manually into the old cert.py. It was simpler than I thought.
I liked the fact that many reimplementations of crypto functions got deleted and delegated to corresponding library calls. 
@robin-jarry , @ThomasFaivre you are welcome to test this latest commit.

**Comment by gpotter2** [comment]
@phaethon 

> those guys know very well about this fork's existence for more than a year and choose not to put a single link to it in their README or elsewhere. You can ask them why.

https://github.com/secdev/scapy/blob/master/scapy/arch/pcapdnet.py#L23

**Comment by johnthagen** [comment]
Was this fixed in 74b79c53aa0ce3b0623d18beeb127002029bd7e0?

**Comment by phaethon** [comment]
This was fixed in the last minor release. Latest code in the repository works with cryptography.io instead of PyCrypto. Closing the issue now.
