### ISSUE TITLE
[Question] Which versions of Python 3 are officially supported?

### ISSUE THREAD

**Issue by johnthagen** [phaethon/scapy#130]
Working on #129 and wondering what versions of Python 3 are/should be officially supported by scapy3k. Seems pretty standard these days to support 3.3+ or 3.4+.

**Edit:**
I did notice this in the README

> Currently, works on Linux, Darwin, Unix and co. Using python 3.4 on Ubuntu and FreeBSD for testing. Windows support in progress.

If we can get Travis working, should scapy3k support be 3.4+?

**Comment by phaethon** [comment]
It is great that you work on Travis support! I have enabled pull requests in Travis. Give me a notice if anything else has to configured in Travis. And, yes, Currently supported versions are 3.4+.
