### ISSUE TITLE
import_hexcap: error with 'raw_input'

### ISSUE THREAD

**Issue by miziaiba** [phaethon/scapy#134]
why use **raw_input** in python3.x?

**Comment by phaethon** [comment]
Large parts of code are migrated from python2 version, and there could certainly be some unintentional and obsolete parts when looking from python3 perspective. Please, give specific code reference.

**Comment by miziaiba** [comment]
In [1]: import_hexcap()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-50f1c2af3a84> in <module>()
----> 1 import_hexcap()

/usr/local/lib/python3.5/dist-packages/scapy/utils.py in import_hexcap()
    981     try:
    982         while 1:
--> 983             **l = raw_input().strip()**
    984             try:
    985                 p += re_extract_hexcap.match(l).groups()[2]

NameError: name 'raw_input' is not defined

**Comment by Inachos** [comment]
I opened a pull request replacing the raw_input query with input at  #135. Apparently, that was the only instance of raw_input in the master branch.
