### ISSUE TITLE
update documentation on github

### ISSUE THREAD

**Issue by tpltnt** [phaethon/scapy#148]
Hi there,

the [current documentation](http://phaethon.github.io/scapy/api/index.html) seems to be as of November 28, 2015. There have been a few changes since then and they should be reflected in the "official" documentation linked from the repository.

Cheers,
tpltnt

**Comment by phaethon** [comment]
Yes, I will regenerate within a ~week. Thanks for the effort!

**Comment by tpltnt** [comment]
Cool ... and you're welcome.

**Comment by phaethon** [comment]
I have updated the documentation and changed the style to alabaster. Have a look.

**Comment by tpltnt** [comment]
The theme looks good. I fixed a few things in #153.
