### ISSUE TITLE
IPv6 sr function bug 

### ISSUE THREAD

**Issue by pegom96** [phaethon/scapy#151]
I've been trying to send ICMPv6EchoRequests messages on my internal network , but I only got response from my router and not from the other connected hosts, but actually I'm able to see their responses with wireshark and using the sniff function of scapy, this and an Issue that I posted on github of scapy2(by mistake :p) leads me to think that there's a bug on line 388 of the inet6.py file in the layers folder of scapy. 

Here's the Issue on the scapy2(the original one) github : https://github.com/secdev/scapy/issues/546

For scapy2 a solution was found(https://github.com/secdev/scapy/pull/547), perhaps we might have the same bug and it would be nice to have an updated version of the inet6.py file

**Comment by gpotter2** [comment]
Hi !

This issue has been resolved on the original scapy fork, which now supports Python 3 !
This fork (scapy3k) is missing many updates, bug fixes and tweaks. You can have a look at
https://github.com/secdev/scapy to get more support !

Have a good day
