### ISSUE TITLE
Integrate slots  classes

### ISSUE THREAD

**Issue by jgatkinsn** [phaethon/scapy#157]
I ran into a problem why trying to customize a field class in your version of scapy. I noticed this [change](https://github.com/secdev/scapy/pull/11) in the original scapy that fixes this along with some memory optimizations using slots.  [Commit](https://github.com/secdev/scapy/commit/438fd87ace9fe15d80fe146faf8814deb7a0fe66)

**Comment by gpotter2** [comment]
Hi !

This issue has been resolved on the original scapy fork, which now supports Python 3 !
This fork (scapy3k) is missing many updates, bug fixes and tweaks. You can have a look at
https://github.com/secdev/scapy to get more support !

Have a good day
