### ISSUE TITLE
Crypto Lib not recognised Mac

### ISSUE THREAD

**Issue by Leocorp** [phaethon/scapy#158]
I have all necessary and required libraries installed on my device but 'Scapy' is unable to recognize and import the 'Crypto Lib' and hence can't decrypt WEP.
I have been battling with this for a while and have found no solution.
Suggestions and fixes are welcomed.

I use:
Macbook: OS Sierra
Python 3.5

**Comment by tmblazek** [comment]
I am on Sierra, and it does work. could you paste the exact error message so I can chack what might be missing?

**Comment by phaethon** [comment]
Please, indicate the source (pypi, GitHub, other), version of scapy, libraries you have installed, and the actual error message. Otherwise, it is quite hard to give any comment.

**Comment by Leocorp** [comment]
Sorry I was away for a while.
Here is a screenshot of my terminal when I start scapy (interactive)

<img width="571" alt="screen shot 2017-04-04 at 00 06 45" src="https://cloud.githubusercontent.com/assets/8627346/24633827/c7bb7298-18ca-11e7-83c7-1ced8d077ad6.png">

I installed using "pip3 install scapy-python3" so I'm sure it was sourced from here.
Concerning the version of libraries I have installed. It is a bit difficult to pinpont which ones came as dependancy installations with scapy. If you (phaethon) could be a little bit specific I'd appreciate it.

**Comment by phaethon** [comment]
This seems to be an older package. When did you install it? The message says that Crypto lib is missing. A recent scapy installed with pip3 would say that cryptography.io is missing (if it is missing). Please, uninstall scapy-python3 and install it again (`pip3 install scapy-python3` should work unless there is something wrong with pip3 in general). 
Alternatively, you can install latest GitHub version using pip3 or setup.py doing:
```
git clone http://github.com/phaethon/scapy
pip3 install ./scapy
```

**Comment by Leocorp** [comment]
Everything is okay now with the exception of the old "Warning: No route found for IPv6 destination".
Thanks

**Comment by phaethon** [comment]
IPv6 warning is because you likely don't have IPv6 configured on the machine. But that's a different issue. Closing this down.
