### ISSUE TITLE
Windows python 3.4

### ISSUE THREAD

**Issue by allan4rf** [phaethon/scapy#16]
Hi ,

I want to know when will the scapy be available on Windows platform for python 3.4 series
I have many libraries thats already built in 3.4 and we cannot port back to older version, 

Is there any way to run Scapy on python 3.4 windows platform ?

many thanks

**Comment by phaethon** [comment]
See issue #15 for discussion on Windows status. python 3.4 is well supported for scapy3k, but there are issues on Windows in general. Dissecting and crafting offline packets is ok, sniffing ok (unless you use wireless), sending is in progress.

**Comment by VivaLaPanda** [comment]
Any progress here, or is the project dead?

**Comment by phaethon** [comment]
The project is alive and kicking. It is working well on Linux and Macos and keep getting improved. What is lacking - Windows users willing to invest some time in testing Windows configuration. The code per se should work on Windows, but there are possible issues with packaging. Also, the general issue with Windows wireless sniffing, which is universal and affects any other tool (e.g. wireshark) demotivates my personal use case.
Are you willing to do some testing on Windows? Packet sending with libdnet should work, but libdnet is nightmare to configure for Windows/python3. Packet sending with winpcap should work, but is not tested.

**Comment by ouje** [comment]
Windows 10, Python 3.4 : Test issue:
ERROR: Windows support for scapy on python3 is currently in development. Sending and receiving packets is not supported yet. Create an issue for your platform request at https://github.com/phaethon/scapy
WARNING: Could not load module netifaces: No module named 'netifaces'
WARNING: No route found for IPv6 destination :: (no default route?)
WARNING: Please, report issues to https://github.com/phaethon/scapy
WARNING: can't import layer inet: 'module' object has no attribute 'IPPROTO_IPIP'
WARNING: can't import layer dhcp: 'module' object has no attribute 'IPPROTO_IPIP'
WARNING: can't import layer dns: 'module' object has no attribute 'IPPROTO_IPIP'
WARNING: can't import layer gprs: 'module' object has no attribute 'IPPROTO_IPIP'
WARNING: can't import layer hsrp: 'module' object has no attribute 'IPPROTO_IPIP'
WARNING: can't import layer inet6: 'module' object has no attribute 'IPPROTO_IPIP'
WARNING: can't import layer dhcp6: 'module' object has no attribute 'IPPROTO_IPIP'
WARNING: can't import layer sctp: 'module' object has no attribute 'IPPROTO_IPIP'
WARNING: can't import layer ipsec: 'module' object has no attribute 'IPPROTO_IPIP'

**Comment by phaethon** [comment]
@ouje issue fixed in latest commit.

**Comment by phaethon** [comment]
I am closing this for now and leaving #15 open for general Windows compatibility discussion. Please, open specific issues you encounter with Windows like @ouje did.

**Comment by phaethon** [comment]
See comments in #15, Windows development is undergoing.
