### ISSUE TITLE
a bug in get_windows_if_list()

### ISSUE THREAD

**Issue by superxlin** [phaethon/scapy#163]
orginal statement:   ps = sp.Popen(['powershell', '-NoProfile', 'Get-WMIObject -class Win32_NetworkAdapter', '|', 'select Name, @{Name="InterfaceIndex";Expression={$_.Index}}, @{Name="InterfaceDescription";Expression={$_.Description}},@{Name="InterfaceGuid";Expression={$_.GUID}}, @{Name="MacAddress";Expression={$_.MacAddress.Replace(":","-")}} | where InterfaceGuid -ne $null', '|', 'fl'], stdout = sp.PIPE, universal_newlines = True)

Index is a wrong name for InterfaceIndex，the correct name must be InterfaceIndex.

**Comment by MordechaiMaman** [comment]
The index is wrong because there is a typo in the command and the command return the index of the WMI object rather then the index of the interface.
I fixed it and send a [pull request](https://github.com/phaethon/scapy/pull/166) , now we will wait 😃
