### ISSUE TITLE
missing release tag 0.20

### ISSUE THREAD

**Issue by anthraxx** [phaethon/scapy#168]
Hi,
I'm a package maintainer and building scapy from github source.
It seems like the 0.20 tag is missing in the git repository, this makes us stuck at 0.19.

It would be amazing if you could push the missing tag.

**Comment by phaethon** [comment]
I added the missing 0.20 tag. Also, there is 0.21 now. You can skip 0.20.

**Comment by anthraxx** [comment]
thanks a lot :smile:
