### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode' (Tried __init__)

### ISSUE THREAD

**Issue by PythonGG** [phaethon/scapy#169]
OS windows 10
Python 3.6
![ss](https://cloud.githubusercontent.com/assets/28899974/26360912/f4b54fc2-400b-11e7-8ca7-5f23d92d59de.png)

Hi guys,I've been troubled with this error for days and tried changing the old value of get_windows_if_list into preferred one(from Index into InterfaceIndex) yet no results,any suggestion guys?

Process finished with exit code 1

**Comment by MordechaiMaman** [comment]
Hi, try to uninstall winpcap (use the wireshark uninstaller) and then install it again.

**Comment by PythonGG** [comment]
Hi,so sorry for the late reply.I'd fixed this problem by:
1.Uninstall winpcap and reinstall again
2.Change the IFace value(But for my case I changed into ANOTHER IFace value :ps = sp.Popen(['powershell', 'Get-NetAdapter', '|', 'select Name, InterfaceIndex, InterfaceDescription, InterfaceGuid, MacAddress', '|', 'fl'], stdout = sp.PIPE, universal_newlines = True) and it Worked!
3.Run as administration(Although this sounds weird but it work for me and is the most crucial steps yet i don't know why)
Anyway Mordechai,thanks for the advice.I hope this can help anyone who have this same problem.
