### ISSUE TITLE
INFO and WARNING for OSX installation

### ISSUE THREAD

**Issue by Wingless-Archangel** [phaethon/scapy#20]
Please find the info and warning for os x installation.

I installed by pip3 on homebrew.
```
$ scapy
INFO: Can't import python gnuplot wrapper . Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: Could not load module netifaces: No module named 'netifaces'
WARNING: No route found for IPv6 destination :: (no default route?)
```

**Comment by phaethon** [comment]
What is your issue? These are just information/warning messages. E.g. if you import PyX, message should go away. If you configure IPV6 for your host, last one should go away, etc.

**Comment by phaethon** [comment]
Closing the issue as additional request on the issue was not received.
