### ISSUE TITLE
Error using PcapReader as an iterator

### ISSUE THREAD

**Issue by lawli3t** [phaethon/scapy#21]
When trying the example from the README i encounter the following error. I have installed scapy-python3 via pip3.

Traceback (most recent call last):
  File "parse.py", line 8, in <module>
    for pkt in pcap_reader:
TypeError: iter() returned non-iterator of type 'PcapReader'

**Comment by phaethon** [comment]
Please, add your OS, python version, and full code sample.

**Comment by lawli3t** [comment]
My OS is Ubuntu 14.04, I am using Python 3.4

Im basically using the exact same snippet from the readme minus the filename so:

with PcapReader('filename.pcap') as pcap_reader:
  for pkt in pcap_reader:
    #do something with the packet

**Comment by phaethon** [comment]
I just did clean install using pip3 on Ubuntu 14.10, python 3.4 and it worked nicely.
Can you repeat it on another host? Are you sure everything is ok with python library environment (e.g. you are sure it is loading scapy-python3 you installed via pip3)?
One more variable is pcap file you use, but I cannot see how it could create error message like that.

**Comment by lawli3t** [comment]
Alright i finally had the time to concern myself with this again. I simply uninstalled the pip version and afterwards cloned the repo and installed it. Has worked fine! Thank you for your effort, i appreciate it!
