### ISSUE TITLE
'IndexError: list index out of range' trying pkt.show()

### ISSUE THREAD

**Issue by elenabdc** [phaethon/scapy#210]
I get this error using Debian 9, python 3.5.3 and scapy-python3 0.21, I also tested it in scapy-python3 version 0.20, 0.19 and 0.18. I'm trying to use multithreading, I don't know if this is relevant or not.

Packets are management frames from a WiFi AP. It shows the first layer as follows:

    ###[ RadioTap dummy ]###
      version   = 0
      pad       = 0
      len       = 36
      present   = TSFT+Flags+Rate+Channel+dBm_AntSignal+RX_Flags+Reset+Ext
      tsft      = 2080
      flags     = short+failed
       rate      = 22
      channel_freq= 34927
      channel_flags= b2+Turbo
      dbm_antsignal= 0
    Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "./concurrent.py", line 39, in run
        print(p.show())
      File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 869, in show
        reprval = f.i2repr(self,fvalue)
      File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 905, in i2repr
        r += [ self.names[i] ]
    IndexError: list index out of range

I think this is a bug and I really appreciate if someone could fix it. Thank you.

Edit:
It works using Python 2 and Scapy, so I think it should be a problem translating python2 to python3.

**Comment by gpotter2** [comment]
Hi !

This issue has been resolved on the original scapy fork, which now supports Python 3 !
This fork (scapy3k) is missing many updates, bug fixes and tweaks. You can have a look at
https://github.com/secdev/scapy to get more support !

Have a good day
