### ISSUE TITLE
scapy fails to launch when netifaces is installed

### ISSUE THREAD

**Issue by tzudot** [phaethon/scapy#22]
(scapy3k)~ ❯❯❯ scapy
```pytb
INFO: Can't import python gnuplot wrapper . Won't be able to plot.
Traceback (most recent call last):
  File "/Users/tzudot/.virtualenvs/scapy3k/bin/scapy", line 25, in <module>
    interact()
  File "/Users/tzudot/.virtualenvs/scapy3k/lib/python3.5/site-packages/scapy/main.py", line 293, in interact
    scapy_builtins = __import__("scapy.all",globals(),locals(),".").__dict__
  File "/Users/tzudot/.virtualenvs/scapy3k/lib/python3.5/site-packages/scapy/all.py", line 25, in <module>
    from .route import *
  File "/Users/tzudot/.virtualenvs/scapy3k/lib/python3.5/site-packages/scapy/route.py", line 163, in <module>
    conf.route=Route()
  File "/Users/tzudot/.virtualenvs/scapy3k/lib/python3.5/site-packages/scapy/route.py", line 22, in __init__
    self.resync()
  File "/Users/tzudot/.virtualenvs/scapy3k/lib/python3.5/site-packages/scapy/route.py", line 31, in resync
    self.routes = read_routes()
  File "/Users/tzudot/.virtualenvs/scapy3k/lib/python3.5/site-packages/scapy/arch/unix.py", line 82, in read_routes
    ifaddr = scapy.arch.get_if_addr(netif)
  File "/Users/tzudot/.virtualenvs/scapy3k/lib/python3.5/site-packages/scapy/arch/__init__.py", line 37, in get_if_addr
    return socket.inet_ntoa(get_if_raw_addr(iff))
TypeError: a bytes-like object is required, not 'NoneType'
```
Is `netifaces` package optional? I see, you have stated this on [stackoverflow.com](http://stackoverflow.com/questions/31910680/python3-installing-scapy-in-os#comment51778906_31912099). What do you suggest, should `netifaces` be installed or not?

**EDIT:** I am running scapy on Mac OS X 10.10.5.

**Comment by phaethon** [comment]
Netifaces is optional. Try removing netifaces and trying again. I will check if they introduced some incompatible changes in netifaces.

**Comment by tzudot** [comment]
Yeah, it works alright without `netifaces` installed. I was wondering if `netifaces` would be useful under certain circumstances for `scapy` or else why at all have this dependency, and is it worthwhile looking into this failure?

**Comment by phaethon** [comment]
netifaces provides OS independent and clean way to determine IP addresses of interfaces. It makes code cleaner, but apparently there have been some changes on the netifaces side as it used to work few months ago.

**Comment by tzudot** [comment]
While debugging the issue, the error came up at line number 66 in [pcapdnet.py](https://github.com/phaethon/scapy/blob/027d93cca3d78aa5291fc6f4141d47701db671b4/scapy/arch/pcapdnet.py#L66). The issue is, looking up of IP addresses of invalid interface, `bridge1` in my case. 

BTW, the routes on the machines as fetched by `netifaces` as in  https://gist.github.com/tzudot/4997d0270530ba978deb but in reality there is not such device as `bridge1`.

**Comment by tzudot** [comment]
On further debugging, I have found that the `route` [gist](https://gist.github.com/tzudot/4997d0270530ba978deb) is the output of `netstat -rn` from file [unix.py](https://github.com/phaethon/scapy/blob/027d93cca3d78aa5291fc6f4141d47701db671b4/scapy/arch/unix.py#L37) on line 37, and not from `netifaces`.

So, it is clear to me know that the error is not from `netifaces` as I might have suggested earlier.

**Comment by phaethon** [comment]
When netifaces is available, it overrides get_if_list function and uses netifaces.interfaces(). Please, provide your actual `netstat -rn` output and `netifaces.interfaces()` output.

**Comment by tzudot** [comment]
```
>>> netifaces.interfaces()
['lo0', 'gif0', 'stf0', 'en1', 'en0', 'en2', 'en3', 'p2p0', 'awdl0', 'bridge0', 'bridge100', 'utun0', 'vboxnet0', 'vboxnet1', 'vboxnet2']
```
```sh
❯❯❯ netstat -rn
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            10.0.2.1           UGSc          167        0     en1
default            link#11            UCSI            0        0 bridge1
10.0.2/24          link#4             UCS             1        0     en1
10.0.2.1/32        link#4             UCS             2        0     en1
10.0.2.1           24:a2:e1:e6:f8:54  UHLWIir       169        7     en1    913
10.0.2.4           24:a2:e1:e6:f8:54  UHLWI           0        9     en1   1199
10.0.2.8/32        link#4             UCS             0        0     en1
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH              1       26     lo0
169.254            link#4             UCS             0        0     en1
192.168.2          link#11            UC              1        0 bridge1

Internet6:
Destination                             Gateway                         Flags         Netif Expire
::1                                     ::1                             UHL             lo0
fde9:2dd0:8e47:d788::/64                fe80::7d36:cd1b:c121:6ace%utun0 Uc            utun0
fde9:2dd0:8e47:d788:7d36:cd1b:c121:6ace link#12                         UHL             lo0
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0
fe80::1%lo0                             link#1                          UHLI            lo0
fe80::%en1/64                           link#4                          UCI             en1
fe80::26a2:e1ff:fee6:f854%en1           24:a2:e1:e6:f8:54               UHLWI           en1
fe80::62f8:1dff:feb8:e72%en1            60:f8:1d:b8:e:72                UHLI            lo0
fe80::%awdl0/64                         link#9                          UCI           awdl0
fe80::a866:eaff:feca:cac9%awdl0         aa:66:ea:ca:ca:c9               UHLI            lo0
fe80::%bridge100/64                     link#11                         UCI        bridge10
fe80::60f8:1dff:fe8b:9264%bridge100     62.f8.1d.8b.92.64               UHLI            lo0
fe80::%utun0/64                         fe80::7d36:cd1b:c121:6ace%utun0 UcI           utun0
fe80::7d36:cd1b:c121:6ace%utun0         link#12                         UHLI            lo0
ff01::%lo0/32                           ::1                             UmCI            lo0
ff01::%en1/32                           link#4                          UmCI            en1
ff01::%awdl0/32                         link#9                          UmCI          awdl0
ff01::%bridge100/32                     link#11                         UmCI       bridge10
ff01::%utun0/32                         fe80::7d36:cd1b:c121:6ace%utun0 UmCI          utun0
ff02::%lo0/32                           ::1                             UmCI            lo0
ff02::%en1/32                           link#4                          UmCI            en1
ff02::%awdl0/32                         link#9                          UmCI          awdl0
ff02::%bridge100/32                     link#11                         UmCI       bridge10
ff02::%utun0/32                         fe80::7d36:cd1b:c121:6ace%utun0 UmCI          utun0
```

**Comment by phaethon** [comment]
Apparently there are differences between interface names as returned by netstat and netifaces. bridge0 vs. bridge 1, bridge100 vs. bridge10. So, this is likely a bug for netifaces for your specific configuration (or generally for bridged interfaces).

**Comment by tzudot** [comment]
Output from `ifconfig` is similar to output of `netifaces`. I guess, `route -nw` is messing up.
```sh
❯❯❯ ifconfig| grep mtu | cut -d':' -f1
lo0
gif0
stf0
en1
en0
en2
en3
p2p0
awdl0
bridge0
bridge100
utun0
vboxnet0
vboxnet1
vboxnet2
```

**Comment by phaethon** [comment]
Current assumption is that interface names are consistent with output from `netstat`. I believe it is a marginal case that `netstat` returns different names than `ifconfig`. So for your case I recommend using scapy without netifaces.

**Comment by tzudot** [comment]
Yeah, this was an issue of a messed up network configuration with `virtualbox`. I have now done a clean install of Mac OS X 10.11, which has cleared up `netstat -rn` output.

**Comment by ciobania** [comment]
I confirm that there is still an issue present.
It seems to me that a fix can be released, to skip or try/except, in the next file:
get_if_addr from arch/__init__.py

The error is reproducible if you have a VM, created with virtualbox, and start the VM.
The only way to use this without changing the actual package, vboxnet interfaces need to be shutdown:
ifconfig vboxnet0 down
ifconfig vboxnet1 down
...
ifconfig vboxnet**n** down

I understand it's not an ideal solution, but nor is reinstalling the system. I currently use my company's laptop, and it's not like I can reinstall anytime I want.
Maybe someone with more knowledge, will provide a better explanation as to why this happens, and maybe **who** is actually meant to "fix" it.

**Comment by phaethon** [comment]
@ciobania did you try using scapy with netifaces switched off? It is optional package as was written before.

**Comment by ciobania** [comment]
Yes, and the behaviour is still present.
In my case, we need netifaces, AND scapy.
They do run fine together, only if I disable the interfaces like in my previous comment.

I am using it home on some personal projects as well, and I have no issue on that machine.

**Comment by phaethon** [comment]
Why do you need netifaces enabled in scapy (especially, as it runs better with it disabled for your case)? conf.use_netifaces disables it for scapy, you can still use netifaces anything else you need in your script.
