### ISSUE TITLE
Fixed pdfdump() and psdump() line drawing references...

### ISSUE THREAD

**Issue by rwhalb** [phaethon/scapy#25]
I have fixed both the pdfdump() and psdump() functions so that line drawing reference now show up in the right side of the drawing:

In file packet.py:

1) Change line 373:
if type(p) is str:
  to:
if type(p) is bytes:

2) Change line 449:
s.append("%02x" % ord(c))
  to:
s.append("%02x" % c)

To test:

IP().pdfdump()

-- Ron Henderson

**Comment by phaethon** [comment]
Changes seem to be good. Can you make a pull request?

**Comment by rwhalb** [comment]
Ok

**Comment by rwhalb** [comment]
Eriks:

 

Done.

 

---Ron Henderson
