### ISSUE TITLE
parsing pcap through paramiko and named_pipe results in bad magic exception

### ISSUE THREAD

**Issue by sander1234567890** [phaethon/scapy#3]
Hi I have a simple application that i was trying to change from python2 to python3.
It's using paramiko to setup a ssh connection to a router and run a tcpdump, pump the results through a named pipe to scapy's sniffer.

It runs perfectly well with python2 and scapy, but i'm running into this exception with python3 and scapy3k, i printed out the magic, and it indeed is not what is expected according to the source.
bad magic: b'T\xe8\x9c0'

WARNING: No route found for IPv6 destination :: (no default route?)
WARNING: Please, report issues to https://github.com/phaethon/scapy
__main__    : DEBUG    running process queue
__main__    : DEBUG    started threads
__main__    : DEBUG    Thread <ThreadingIntervalTimer(Thread-1, started daemon 140516139489024)> isDeamon: True
__main__    : DEBUG    Thread <StoppableThread(Thread-2, started daemon 140516131096320)> isDeamon: True
__main__    : DEBUG    Thread <StoppableThread(Thread-3, started daemon 140516122703616)> isDeamon: True
paramiko.transport: DEBUG    starting thread (client mode): 0x39af510
paramiko.transport: INFO     Connected (version 2.0, client dropbear_2014.63)
...
paramiko.transport: DEBUG    userauth is OK
paramiko.transport: INFO     Authentication (publickey) successful!
paramiko.transport: DEBUG    [chan 0] Max packet in: 32768 bytes
paramiko.transport: DEBUG    [chan 0] Max packet out: 32768 bytes
paramiko.transport: DEBUG    Secsh channel 0 opened.
paramiko.transport: DEBUG    [chan 0] Sesch channel 0 request ok
__main__    : DEBUG    read 24bytes
__main__    : DEBUG    read 394bytes
bad magic: b'T\xe8\x9c0'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "wifi-mac-scraper.py", line 68, in run
    self.target(*self.args)
  File "wifi-mac-scraper.py", line 117, in sniffer
    scapy.all.sniff(offline=_named_pipe_path, prn=process_packet, store=0)
  File "/usr/local/lib/python3.2/dist-packages/scapy/sendrecv.py", line 568, in sniff
    s = PcapReader(offline)
  File "/usr/local/lib/python3.2/dist-packages/scapy/utils.py", line 625, in __init__
    RawPcapReader.__init__(self, filename)
  File "/usr/local/lib/python3.2/dist-packages/scapy/utils.py", line 549, in __init__
    raise Scapy_Exception("Not a pcap capture file (bad magic)")
scapy.error.Scapy_Exception: Not a pcap capture file (bad magic)

^[[A^C__main__    : DEBUG    received sigal: 2
__main__    : DEBUG    stopped threads
__main__    : DEBUG    Stopped ThreadingIntervalTimer

The code in question is:

def sniffer(_named_pipe_path, _q):
    scapy.all.sniff(offline=_named_pipe_path, prn=process_packet, store=0)

def remotetcpdump_ssh(_named_pipe_path):

    sshclient = paramiko.SSHClient()
    _named_pipe = open(_named_pipe_path, 'wb', 0)

    try:
        sshclient.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        sshclient.connect('xxx,xxx,xxx,xxx', username='xxxx', password='xxxx')

        chan = sshclient.get_transport().open_session()
        chan.exec_command('/usr/sbin/tcpdump -q -U -w - -i moni0 "wlan type mgt subtype probe-req or wlan type mgt subtype assoc-req or wlan type mgt subtype reassoc-req"')

        while True:
            if chan.recv_ready():
                data = chan.recv(66560)
                logger.debug("read " + str(len(data)) + "bytes")
                _named_pipe.write(data)
            time.sleep(0.1)

    except paramiko.SSHException as _e:
        logger.debug("SSH exception: %s" % _e)
        _named_pipe.close()
        sshclient.close()
        raise

    _named_pipe.close()
    sshclient.close()

def remotetcpdump(_named_pipe_path):
    while True:
        try:
            remotetcpdump_ssh(_named_pipe_path)
        except:
            time.sleep(5)
            remotetcpdump_ssh(_named_pipe_path)

**Comment by sander1234567890** [comment]
Hmm  it seems it's not looking at the first 4 bytes of the pcap, for this run i got:
bad magic: b'T\xe8\xc2\xdb'

While the pcap has:
00000000h: A1 B2 C3 D4 00 02 00 04 00 00 00 00 00 00 00 00 ; ¡²ÃÔ............
00000010h: 00 00 FF FF 00 00 00 7F 54 E8 C2 DB 00 01 24 6A ; ..ÿÿ...TèÂÛ..$j

So you see the offset seems to be wrong some how.

**Comment by sander1234567890** [comment]
Whoops accidently closed it .. sorry

**Comment by phaethon** [comment]
On python2.7 gzip.open when reading from named pipe generates different exception even before reading 4 bytes:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 288, in _read
    pos = self.fileobj.tell()   # Save current position
IOError: [Errno 29] Illegal seek

**Comment by phaethon** [comment]
I changed utils.py code to:
        try:
            if not stat.S_ISREG(os.stat(filename).st_mode):
              raise IOError("GZIP detection works only for regular files")
            self.f = gzip.open(filename,"rb")
            magic = self.f.read(4)
        except IOError:
            self.f = open(filename,"rb")
            magic = self.f.read(4)
It should work now for your case. Possible future improvement would be reading gzip over pipe, but I did not have any good ideas how to do it in a nice way.
