### ISSUE TITLE
problem with dissection of DNSRR 

### ISSUE THREAD

**Issue by interlocuteur** [phaethon/scapy#41]
I think I found a problem with dissection of DNS answers.
The problem is easy to duplicate:
```
def filt(p):
  if p.haslayer( DNSRR):
    for i in range( 0, p[DNS].ancount):
      print( p[DNS].an[i].rdata, p[DNS].an[i].rrname.decode())

s=sniff(count=50, lfilter=filt)
```
Here's an excerpt of what I got:
```
184.150.182.119 plus.l.google.com.
184.150.182.99 plus.l.google.com.
184.150.182.89 plus.l.google.com.
b'plus.l.google.com.' apis.google.com.
2607:f8b0:400b:806::1006 plus.l.google.com.
184.150.153.168 encrypted-tbn2.gstatic.com.
```
Clearly, the 4th line in the result is wrong; rdata must not be a name.
My preliminary analysis show that scapy has a problem when dissecting a DNSRR with an IPV6 address.
Looking at s in the previous code example should prove it.
Note: I set a count of 50 in sniff. Depending on the sites you visit (do they use IPV6?), you may need more or less).

I haven't checked if the problem was in Scapy V2

**Comment by syakesaba** [comment]
$ nslookup apis.google.com
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
apis.google.com	canonical name = plus.l.google.com.
Name:	plus.l.google.com
Address: 173.194.38.206
Name:	plus.l.google.com
Address: 173.194.38.201
Name:	plus.l.google.com
Address: 173.194.38.200
Name:	plus.l.google.com
Address: 173.194.38.194
Name:	plus.l.google.com
Address: 173.194.38.197
Name:	plus.l.google.com
Address: 173.194.38.192
Name:	plus.l.google.com
Address: 173.194.38.193
Name:	plus.l.google.com
Address: 173.194.38.199
Name:	plus.l.google.com
Address: 173.194.38.196
Name:	plus.l.google.com
Address: 173.194.38.195
Name:	plus.l.google.com
Address: 173.194.38.198

It is DNS CNAME.
I think its not issue.
