### ISSUE TITLE
Windows 10 64bit WinError126

### ISSUE THREAD

**Issue by gantlion** [phaethon/scapy#42]
Hi all, when I try running:
   from scapy.all import *

I get the error: [WinError 126] The specified module could not be found

After looking at the traceback in ipython it looks like an exception is found when trying to access  _lib=CDLL('wpcap.dll').

I installed scapy-python3 using pip, any ideas?

**Comment by phaethon** [comment]
You need to install WinPcap, too.

**Comment by gantlion** [comment]
Thanks, I missed that bit of the instructions
