### ISSUE TITLE
segfault caused by pcap_get_selectable_fd on Mac OS X 10.10

### ISSUE THREAD

**Issue by Congee** [phaethon/scapy#49]
Code resulting in segfault:
``` python
from scapy.all import *
p = IP(dst = 'www.bing.com') / TCP(dport = 80) / Raw(b'Some raw bytes')
# to see packet content as bytes use bytes(p) not str(p)
sr1(p)
```
You can get some details by  `man pcap_get_selectable_fd` 
This info may be helpful:

INFO: Can't import matplotlib. Not critical, but won't be able to plot.
INFO: Can't import networkx. Not criticial, but won't be able to draw network graphs.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: Could not load module netifaces: No module named 'netifaces'
INFO: No IPv6 support in kernel
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
INFO: Please, report issues to https://github.com/phaethon/scapy
INFO: Can't import python Crypto lib. Won't be able to decrypt WEP.
INFO: Can't import python Crypto lib. Disabled certificate manipulation tools
Python 3.5.1 (default, Dec  7 2015, 21:59:08)

I'm not capable of debuging scapy due to some trivial ctypes related code. So.... Any suggestions?

**Comment by phaethon** [comment]
Can you test it on a clean machine? I have not seen another user with the same issue, and your testcase is so generic, that almost everybody would try something like that.

**Comment by 0x5e** [comment]
sudo python will be ok

**Comment by Congee** [comment]
@0x5e :D, it works. Do you know why?
