### ISSUE TITLE
IPv6 ICMP Echo Request is sent to broadcast MAC-address

### ISSUE THREAD

**Issue by spron-in** [phaethon/scapy#6]
Hi,

I've tried to send a crafted IPv6 ICMP Echo Request via scapy for Python 3.4 and noticed the warning:

```
>>> sr1(IPv6(dst='2a00:1450:4013:c00::71')/ICMPv6EchoRequest(), timeout=1)
Begin emission:
.WARNING: Mac address to reach destination not found. Using broadcast.
Finished to send 1 packets.
....................................................................................
Received 85 packets, got 0 answers, remaining 1 packets
```

The dump file could be found [here](https://www.dropbox.com/s/k6rdattp7v65x3y/ipv6echo.pcap?dl=0). You can see, that Echo Request frame is sent to broadcast MAC-address FF:FF:FF:FF:FF:FF.

The same command with version for python 2 works okay. 
Am I doing smth wrong? I've tried setting dst mac-address in Ether, but the packet is still sent to broadcast.

Cheers.

**Comment by phaethon** [comment]
Your code seems ok. What platform (linux, mac?) are you using?

**Comment by spron-in** [comment]
Hi, it is linux. Debian.
`3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux`
