### ISSUE TITLE
Documentation: Move all API elements to top level

### ISSUE THREAD

**Issue by jtpereyda** [phaethon/scapy#60]
It's hard to figure out what classes and modules are available. Best workflow I have now is to read through code, grep, or use Google.

One idea is to put everything at the top level to simplify the API. The best approach I know of is to use `__init__.py`. Check out pip for an example: https://github.com/pypa/pip/blob/develop/pip/__init__.py

This would have two major benefits:
1. No more trying to figure out which file to include ("Of course IP is in Layer2, what did you expect? Layer3?").
2. Incidental documentation of what's in the API.

**Comment by phaethon** [comment]
Could you clarify more? Currently, you can do `from scapy.all import *` and not care in which exact module IP sits. Is this not overlapping?
Also, there are `ls()` and `lsc()` commands.

**Comment by jtpereyda** [comment]
It looks like scapy.all will work. Thanks.

I haven't tried ls() and lsc() before. They look handy, though, I'll have to try them. Do they list all features from scapy?

**Comment by phaethon** [comment]
`lsc` lists all commands, and `ls` lists all loaded layers.
