### ISSUE TITLE
set Ether src to 'aa:aa:aa:aa:aa:aa' did not work

### ISSUE THREAD

**Issue by 0x5e** [phaethon/scapy#62]
I'm trying to send PPPoED packet with custom mac address, but seems very strange.. On wireshark I can see two same packet with different ether src 'aa:aa:aa:aa:aa:aa' and 'a4:5e:60:b7:75:7b'(original mac address). 
Why 'a4:5e:60:b7:75:7b' packet appears, and seems no one has received 'aa:aa:aa:aa:aa:aa' packet?
![image](https://cloud.githubusercontent.com/assets/5144674/12866134/93a69786-ccfd-11e5-8d57-1e7b092c3f27.png)

[duplicate.pcap.zip](https://github.com/phaethon/scapy/files/120616/duplicate.pcap.zip)

**Comment by 0x5e** [comment]
this two packet have same content

**Comment by phaethon** [comment]
I need to see how do you craft and send the packet to be able to comment. Also, add information on platform and network interfaces (conf.route output). There are circumstances when layer 2 sending is non-functional

**Comment by 0x5e** [comment]
Mac OS X 10.11.3
Python 3.5.1

`
>>> conf.route
Network         Netmask         Gateway         Iface           Output IP
0.0.0.0         0.0.0.0         192.168.31.1    en0             192.168.31.233 
127.0.0.0       255.0.0.0       0.0.0.0         lo0             127.0.0.1      
127.0.0.1       255.255.255.255 0.0.0.0         lo0             127.0.0.1      
169.254.0.0     255.255.0.0     0.0.0.0         en0             192.168.31.233 
192.168.31.0    255.255.255.0   0.0.0.0         en0             192.168.31.233 
192.168.31.1    255.255.255.255 0.0.0.0         en0             192.168.31.233 
192.168.31.1    255.255.255.255 0.0.0.0         en0             192.168.31.233 
192.168.31.166  255.255.255.255 0.0.0.0         en0             192.168.31.233 
192.168.31.233  255.255.255.255 0.0.0.0         en0             192.168.31.233 
192.168.31.233  255.255.255.255 0.0.0.0         lo0             127.0.0.1      
192.168.31.255  255.255.255.255 0.0.0.0         en0             192.168.31.233 
255.255.255.255 255.255.255.255 0.0.0.0         en0             192.168.31.233 
`

I send packet like this
`
p = Ether(dst='a4:5e:60:b7:75:7b',src='aa:aa:aa:aa:aa:aa') / PPPoED()
sendp(p, iface='en0')
`

But it's very strange.. For example, I send 7 packets but 9 packets catched on wireshark :
![image](https://cloud.githubusercontent.com/assets/5144674/13177216/9ad64e66-d752-11e5-9e76-49daa04344ad.png)

'a4:5e:60:b7:75:7b' is my mac address,
