### ISSUE TITLE
API Reference

### ISSUE THREAD

**Issue by jtpereyda** [phaethon/scapy#64]
From the first time I used scapy I've always wanted an API reference. To figure out how to use scapy in a program, there is no easily accessed API reference as far as I know.

The `ls()` and `lsc()` commands list what you can do in the scapy interpreter, but I'm looking for the classes and modules that can be used in a Python script.

I don't know how many of these features exist beyond `ls()`/`lsc()`, but one example is [PcapWriter](http://stackoverflow.com/a/20780224/461834).

I'm not sure about the best way to get to an explicit API reference, but we can use Sphinx and readthedocs.org for hosting.

**Comment by phaethon** [comment]
There is some documentation on http://phaethon.github.io/scapy/
It is modified original scapy user guide with corrections and additions for scapy3k. Also, there are some cookbook entries more specific to scapy3k. Idea is that all API functions, which shall be used by developers (except the ones developing/improving scapy itself) is described on these pages. 
Sphinx is already used there and the same page can be used for hosting. Current documentation sources are in the folder doc/scapy in this repository. The only thing lacking is some work to be done. In my personal task list it is not at the top. I would be very supportive and thankful to anybody taking care of this topic :) The first thing would be to identify the most crucial parts (classes, methods), which are missing or incorrectly represented.

**Comment by phaethon** [comment]
@jtpereyda would you be interested to join the effort to improve documentation?

**Comment by jtpereyda** [comment]
@phaethon I would be but no capability right now. I'll keep it in mind for the future. Thanks.
