### ISSUE TITLE
Large PCAP files consume too much memory

### ISSUE THREAD

**Issue by Rainmaker52** [phaethon/scapy#7]
I'm facing an issue where I have a dump file of over 4 GB to be loaded.
This consumes the entire 16 GB of memory in my computer, and causes swapping and other unwanted stuff.

The "patch" for this problem has been posted several years back:
http://permalink.gmane.org/gmane.comp.security.scapy.general/4462

It would be nice to include this into scapy.

**Comment by Rainmaker52** [comment]
After actually trying this, the patch proposed in the mailthread above doesn't seem to be working as-is.

I found another (and, I believe, better) workaround, by modifying the caller:

    myreader = scapy.PcapReader(filename)

    while True:
        packet = myreader.read_packet()
        if packet is None:
            break
        ...

Committed 846000 packets sucessfully, with memory usage under 200 MB.

**Comment by phaethon** [comment]
Should we change anything in scapy?
Sure, if you process packets one by one and don't use the list of all packets, it consumes less memory, but would not fit all use cases. Also, iterator interface can be used for reading packets.

**Comment by Rainmaker52** [comment]
In my opinion, yes.

While the above is a workaround, the scappy.rdpcap method is currently the way to read in PCAP files.

This method is currently very limited, because it requires the entire contents of the PCAP to be loaded into memory. Providing a generator / iterator interface, will allow for much larger dumps to be processed.

**Comment by phaethon** [comment]
There are 2 classes:
PcapReader - decodes all packets immediately
RawPcapReader - does not decode packets

Both of them have iterator interface (which I fixed in latest commit). So you can write in your case:
```
with PcapReader('file.pcap') as pr:
  for p in pr:
    ...do something with a packet p...
```

**Comment by phaethon** [comment]
And this is not a workaround, it is safe to use. Lack of documentation on this is the real issue.

**Comment by phaethon** [comment]
I have updated README to include this usage example.
