### ISSUE TITLE
.WARNING: __del__: don't know how to close the file descriptor

### ISSUE THREAD

**Issue by nayanseth** [phaethon/scapy#70]
This is issue is for Mac OS X 10.11.2 and python version is 2.7.6 (Scapy 2.3.2)

<img width="872" alt="screen shot 2016-02-25 at 5 47 00 pm" src="https://cloud.githubusercontent.com/assets/3462785/13339688/cc88b5d6-dbe7-11e5-806d-e1693ec2fee3.png">

**Comment by phaethon** [comment]
If you have python 2.7.6 it is a different project. This project is python3 only. See www.secdev.org
