### ISSUE TITLE
full scapy tutorial

### ISSUE THREAD

**Issue by sheenawadhwa** [phaethon/scapy#77]
I'm new to scapy. Am not able how to use scapy and how to import scapy modules in python script. Can any one help me to by showing simple tutorial example. I read documentation but there is no full script.

**Comment by phaethon** [comment]
You can start with these tutorial series: https://thepacketgeek.com/series/building-network-tools-with-scapy/
It is hard to write all encompassing scapy tutorial. Scapy is very powerful and people use it for very different reasons: analyze traffic, simulate network clients/servers for various protocols, manipulate packet parameters, etc. A lot of options where to start. Also, people differ in their knowledge of network protocols a lot. I will appreciate specific feedback on topics that should be covered in tutorial.
