### ISSUE TITLE
unknown os's with p0f module

### ISSUE THREAD

**Issue by lamazavr** [phaethon/scapy#85]
Hi, I'd like to use p0f module to determine os's on local network. 
But when I run:

```
>>> load_module("p0f")
>>> a=sniff(prn=prnp0f)
```

I see only unknown:

```
192.168.1.103:ssh - UNKNOWN [260:64:1.0:0:.:AFD:?:?]
  -> 192.168.1.95:59213 (PA)
192.168.1.103:ssh - UNKNOWN [260:64:1.0:0:.:AFD:?:?]
  -> 192.168.1.95:59213 (PA)
```

I use raspbian with p0f 2.0.8 and scapy 3.0.0.
What possible solutions may be for such problem?

**Comment by phaethon** [comment]
Scapy is using p0f database. If there are no records in p0f matching this Mac address, then this is what you get. p0f is not actively maintained. p0f v3 is not integrated with scapy (at least not yet). You can write a script using scapy and p0f v3 (if p0f v3 works better for your traffic).
