### ISSUE TITLE
utf-8 error

### ISSUE THREAD

**Issue by pintman** [phaethon/scapy#90]
I submitted the following issue at secdev/scapy and was asked to post it here again
https://github.com/secdev/scapy/issues/150

The following error occured in OpenSuse 13.2. It seems there are some umlauts in /etc/services that caused the error. Changing line 110 in scapy/data.py in load_services(filename) from

```
f=open(filename)
```

into 

```
f=open(filename, encoding='latin1')
```

solved the problem for me.

Here is the error message:

Traceback (most recent call last):
  File "/home/marco/tmp/tmp.py", line 1, in <module>
    from scapy.all import sniff
  File "/usr/lib/python3.4/site-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/lib/python3.4/site-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/lib/python3.4/site-packages/scapy/data.py", line 185, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/lib/python3.4/site-packages/scapy/data.py", line 111, in load_services
    for l in f:
  File "/usr/lib64/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3269: invalid continuation byte

Here are some infos about the file /etc/services in question:

If position 3269 is meant to be 0xCC5 in hex, I can give the following dump from hexdump although I don't see a 0xe9 there.

00000ca0  20 50 72 6f 63 65 73 73  20 20 5b 42 65 72 6e 69  | Process  [Berni|
00000cb0  65 5f 56 6f 6c 7a 5d 0a  23 20 20 20 20 20 20 20  |e_Volz].#       |
00000cc0  20 20 20 20 20 20 20 20  20 20 20 34 2f 74 63 70  |           4/tcp|
00000cd0  20 20 20 20 20 20 20 20  55 6e 61 73 73 69 67 6e  |        Unassign|
00000ce0  65 64 20 0a 23 20 20 20  20 20 20 20 20 20 20 20  |ed .#           |

Searching for e9 yields to the following output

~$ hexdump -C /etc/services |grep 'e9 '
000a2cc0  5f 53 6f 6c 6c e9 5d 0a  23 20 20 20 20 20 20 20  |_Soll.].#       |
000bce20  5d 0a 69 63 6c 2d 74 77  6f 62 61 73 65 39 20 20  |].icl-twobase9  |
000bce60  6c 2d 74 77 6f 62 61 73  65 39 20 20 20 20 20 20  |l-twobase9      |
000bce80  69 63 6c 2d 74 77 6f 62  61 73 65 39 20 20 5b 4a  |icl-twobase9  [J|
000e4160  20 20 46 41 55 43 4f 4e  4e 45 54 20 49 6e 67 e9  |  FAUCONNET Ing.|
00121ba0  6e 5f 44 5f 53 6f 6c 6c  e9 20 20 20 20 20 20 20  |n_D_Soll.       |
00121bc0  6c 6c e9 20 20 20 20 20  20 20 20 20 20 20 20 56  |ll.            V|
00121e30  6e 64 65 72 65 72 20 20  20 20 20 20 20 53 e9 62  |nderer       S.b|
00125230  20 20 20 20 20 20 20 20  20 20 20 20 53 74 e9 70  |            St.p|

Maybe some of this output might help.

**Comment by phaethon** [comment]
Yes, this is the right place for the issue. I will have a look, but if you could attach full services file it could help.

**Comment by phaethon** [comment]
Do you know what encoding /etc/services is in? Is using latin1 the correct solution?

**Comment by pintman** [comment]
I don't know whether the file contains "confidential" information. Therefore I am not sure if I should upload it. But the following output may be helpful:

    /etc$ file -i services 
    services: text/plain; charset=us-ascii

**Comment by phaethon** [comment]
/etc/services normally don't contain any confidential information. In fact normally it is unchanged from the software installation (there are exceptions of course). If the charset of the file really was us-ascii this issue would not happen. As it is non-English version, which creates a problem, it would be quite a hassle for me to get it myself.

**Comment by pintman** [comment]
I uploaded my services-file. There are a lot of names at the end of the file that might cause the problem.

[services.zip](https://github.com/phaethon/scapy/files/266474/services.zip)

**Comment by vpereira** [comment]
having the same problem.

my traceback:

```
vpereira@kimura:~/scapy> scapy
Traceback (most recent call last):
  File "/usr/bin/scapy", line 23, in <module>
    from scapy.main import interact
  File "/usr/lib/python3.4/site-packages/scapy/main.py", line 16, in <module>
    from . import utils
  File "/usr/lib/python3.4/site-packages/scapy/utils.py", line 20, in <module>
    from .config import conf
  File "/usr/lib/python3.4/site-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/lib/python3.4/site-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/lib/python3.4/site-packages/scapy/data.py", line 110, in load_services
    for l in f:
  File "/usr/lib64/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3269: invalid continuation byte

```

**Comment by sumpfgottheit** [comment]
I have the same error on OpenSuse Tumbletweed vom 2016-11-16. The /etc/services file contains at least a few Umlaut-'ö' characters in the latin1 representation 0xf6. As python3 opens the file in utf-8, we get these error. 

A `open('/etc/services', errors='ignore')` should fix it. The file could also be opened in latin1. (see the code below). I don't know in which encoding /etc/services is expected, but ignoring the error should be right in this case.

```
In [2]: with open('/etc/services') as f:
   ...:     f.readlines()
   ...: 
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-677bf46cb985> in <module>()
      1 with open('/etc/services') as f:
----> 2     f.readlines()

/home/saf/devel/_virtualenvs/scapy/lib64/python3.5/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 4953: invalid start byte

In [3]: with open('/etc/services', encoding='latin1') as f:
   ...:     f.readlines()
   ...: 

In [4]: with open('/etc/services', errors='ignore') as f:
   ...:     f.readlines()
   ...: 

```

**Comment by sumpfgottheit** [comment]
See #114

**Comment by jackinglew001** [comment]
raceback (most recent call last):
  File "download.py", line 10, in <module>
    from scapy.all import rdpcap
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by phaethon** [comment]
@jackinglew001 you seem to use python2.7. scapy3k works only with python3.

**Comment by pintman** [comment]
Closing this issue since PR of @sumpfgottheit has been merged.
