### ISSUE TITLE
DNS over TCP

### ISSUE THREAD

**Issue by lawnmowerlatte** [phaethon/scapy#92]
I'm trying to use Scapy to test DNS over TCP, but the response packet is returning a `Raw` object, not `DNS`:

```
fqdn = "test.fqdn.tld"
server = "192.168.0.1"
rr = "A"
ip = IP(dst=server)
tcp = TCP(dport=53)
dns = DNS(rd=1, qd=DNSQR(qname=fqdn, qtype=rr))

syn = TCP(sport=RandNum(1024,65535),
          dport=tcp.dport,
          flags="S",
          seq=42)
synack = sr1(ip/syn)

ack = TCP(sport=synack.dport,
          dport=tcp.dport,
          flags="A",
          seq=synack.ack,
          ack=synack.seq + 1)
send(ip/ack)

dnsq = TCP(sport=synack.dport,
           dport=tcp.dport,
           flags="PA",
           seq=synack.ack,
           ack=synack.seq + 1)/dns_with_size
dnsr = sr1(ip/dnsq, filter='tcp[13] & 8 != 0')
```

If I look for the DNS layer, it throws an `IndexError: Layer [DNS] not found`, but if I look for the Raw data, it's the expected bytes from the response:

```
>>> dnsr[Raw]
<Raw  load=b'\x00X\x00\x00\x85\x00\x00\x01\x00\x01\x00\x03\x00\x00\x04test\x00\x00\x01\x00\x01\xc0\x0c\x00\x01\x00\x01\x00\x00\x0e\x10\x00\x04\x01\x01\x01\x01\xc0\x0c\x00\x02\x00\x01\x00\x00\x0e\x10\x00\x04\x02ns\x00\xc0\x0c\x00\x02\x00\x01\x00\x00\x0e\x10\x00\x05\x03ns2\x00\xc0\x0c\x00\x02\x00\x01\x00\x00\x0e\x10\x00\x05\x03ns3\x00' |>
```

It looks like DNS over TCP is not supported. I found a [patch](https://gist.github.com/jpmens/5574263) for DNS TCP, maybe this can be pulled in to add support?

**Comment by phaethon** [comment]
If you could apply and test the patch, and create the pull request, we could quickly solve the problem. Also, please, add a test to regression test suite. I will assist with any difficulties if such will arise.

**Comment by lawnmowerlatte** [comment]
Better late than never. In addition to the unit testing, I've verified that this functions within my project.

**Comment by phaethon** [comment]
No reason. Closing down.
